local weapons = {
    chainsword_p1_m1 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.3,
    },
    chainsword_p1_m2 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.3,
    },
    chainsword_2h_p1_m1 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.3,
    },
    chainsword_2h_p1_m2 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.3,
    },
    chainaxe_p1_m1 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.5,
    },
    chainaxe_p1_m2 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.5,
    },
    combataxe_p1_m1 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    combataxe_p1_m2 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    combataxe_p1_m3 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    combataxe_p2_m1 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    combataxe_p2_m2 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    combataxe_p2_m3 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    combataxe_p3_m1 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    combataxe_p3_m2 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.3,
    },
    combataxe_p3_m3 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.3,
    },
    combatknife_p1_m1 = {
        action_special              = true,
        interrupt_sprinting_special = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    combatknife_p1_m2 = {
        action_special              = true,
        interrupt_sprinting_special = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    combatsword_p1_m1 = {
        action_special              = true,
        special_parry               = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    combatsword_p1_m2 = {
        action_special              = true,
        special_parry               = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    combatsword_p1_m3 = {
        action_special              = true,
        special_parry               = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    combatsword_p2_m1 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    combatsword_p2_m2 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    combatsword_p2_m3 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    combatsword_p3_m1 = {
        action_special              = true,
        special_parry               = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    combatsword_p3_m2 = {
        action_special              = true,
        special_parry               = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    combatsword_p3_m3 = {
        action_special              = true,
        special_parry               = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    forcesword_p1_m1 = {
        pressing_buffer             = 0.2,
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.3,
    },
    forcesword_p1_m2 = {
        pressing_buffer             = 0.2,
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.3,
    },
    forcesword_p1_m3 = {
        action_special              = true,
        ignore_active_special       = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    forcesword_2h_p1_m1 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    forcesword_2h_p1_m2 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    powermaul_p1_m1 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    powermaul_p1_m2 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    powermaul_p2_m1 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    powermaul_2h_p1_m1 = {
        action_special              = true,
        ignore_active_special       = true,
        special_releases_action_one = true,
        special_releases_action_two = true,
        promise_buffer              = 1.0,
    },
    powermaul_shield_p1_m1 = {
        action_special              = true,
        special_needs_charges       = 25,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    powermaul_shield_p1_m2 = {
        action_special              = true,
        special_needs_charges       = 25,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    powersword_p1_m1 = {
        action_special              = true,
        ignore_active_special       = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    powersword_p1_m2 = {
        action_special              = true,
        ignore_active_special       = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    powersword_p2_m1 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    powersword_p2_m2 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    powersword_2h_p1_m1 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    powersword_2h_p1_m2 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    thunderhammer_2h_p1_m1 = {
        action_special              = true,
        ignore_active_special       = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    thunderhammer_2h_p1_m2 = {
        action_special              = true,
        ignore_active_special       = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    dual_shivs_p1_m1 = {
        action_special              = true,
        special_needs_charges       = 1,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    dual_shivs_p1_m2 = {
        action_special              = true,
        special_needs_charges       = 1,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    saw_p1_m1 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    crowbar_p1_m1 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.3,
    },
    ogryn_combatblade_p1_m1 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    ogryn_combatblade_p1_m2 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    ogryn_combatblade_p1_m3 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    ogryn_club_p1_m1 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    ogryn_club_p1_m2 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.3,
    },
    ogryn_club_p1_m3 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.3,
    },
    ogryn_club_p2_m1 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    ogryn_club_p2_m2 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    ogryn_club_p2_m3 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    ogryn_powermaul_p1_m1 = {
        action_special              = true,
        special_needs_charges       = 1,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    ogryn_powermaul_slabshield_p1_m1 = {
        action_special              = false,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    ogryn_pickaxe_2h_p1_m1 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.5,
    },
    ogryn_pickaxe_2h_p1_m2 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.5,
    },
    ogryn_pickaxe_2h_p1_m3 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.5,
    },
    autogun_p1_m1 = {
        action_special              = true,
        action_reload               = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        reload_releases_action_one  = true,
        reload_releases_action_two  = false,
        promise_buffer              = 1.0,
    },
    autogun_p1_m2 = {
        action_special              = true,
        action_reload               = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        reload_releases_action_one  = true,
        reload_releases_action_two  = false,
        promise_buffer              = 1.0,
    },
    autogun_p1_m3 = {
        action_special              = true,
        action_reload               = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        reload_releases_action_one  = true,
        reload_releases_action_two  = false,
        promise_buffer              = 1.0,
    },
    autogun_p2_m1 = {
        action_special              = true,
        action_reload               = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        reload_releases_action_one  = true,
        reload_releases_action_two  = false,
        promise_buffer              = 1.0,
    },
    autogun_p2_m2 = {
        action_special              = true,
        action_reload               = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        reload_releases_action_one  = true,
        reload_releases_action_two  = false,
        promise_buffer              = 1.0,
    },
    autogun_p2_m3 = {
        action_special              = true,
        action_reload               = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        reload_releases_action_one  = true,
        reload_releases_action_two  = false,
        promise_buffer              = 1.0,
    },
    autogun_p3_m1 = {
        action_special              = true,
        action_reload               = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        reload_releases_action_one  = true,
        reload_releases_action_two  = false,
        promise_buffer              = 1.0,
    },
    autogun_p3_m2 = {
        action_special              = true,
        action_reload               = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        reload_releases_action_one  = true,
        reload_releases_action_two  = false,
        promise_buffer              = 1.0,
    },
    autogun_p3_m3 = {
        action_special              = true,
        action_reload               = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        reload_releases_action_one  = true,
        reload_releases_action_two  = false,
        promise_buffer              = 1.0,
    },
    autopistol_p1_m1 = {
        action_special              = true,
        action_reload               = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        reload_releases_action_one  = true,
        reload_releases_action_two  = false,
        promise_buffer              = 1.0,
    },
    bolter_p1_m1 = {
        interval_do_promise         = 0.25, -- Without this, Weapon will stuck on sight even released right click when immediately do special after shooting
        action_special              = true,
        action_reload               = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        reload_releases_action_one  = true,
        reload_releases_action_two  = false,
        promise_buffer              = 1.0,
    },
    bolter_p1_m2 = {
        interval_do_promise         = 0.25, -- Without this, Weapon will stuck on sight even released right click when immediately do special after shooting
        action_special              = true,
        action_reload               = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        reload_releases_action_one  = true,
        reload_releases_action_two  = false,
        promise_buffer              = 1.0,
    },
    boltpistol_p1_m1 = {
        interval_do_promise         = 0.25, -- Without this, Weapon will stuck on sight even released right click when immediately do special after shooting
        action_special              = true,
        action_reload               = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        reload_releases_action_one  = true,
        reload_releases_action_two  = false,
        promise_buffer              = 1.0,
    },
    boltpistol_p1_m2 = {
        interval_do_promise         = 0.25, -- Without this, Weapon will stuck on sight even released right click when immediately do special after shooting
        action_special              = true,
        action_reload               = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        reload_releases_action_one  = true,
        reload_releases_action_two  = false,
        promise_buffer              = 1.0,
    },
    flamer_p1_m1 = {
        action_special              = true,
        action_reload               = true,
        special_releases_action_one = false,
        special_releases_action_two = false,
        reload_releases_action_one  = false,
        reload_releases_action_two  = false,
        promise_buffer              = 1.0,
    },
    forcestaff_p1_m1 = {
        action_special              = true,
        special_releases_action_one = false,
        special_releases_action_two = true,
        promise_buffer              = 1.0,
    },
    forcestaff_p2_m1 = {
        action_special              = true,
        special_releases_action_one = false,
        special_releases_action_two = true,
        promise_buffer              = 1.0,
    },
    forcestaff_p3_m1 = {
        action_special              = true,
        special_releases_action_one = false,
        special_releases_action_two = true,
        promise_buffer              = 1.0,
    },
    forcestaff_p4_m1 = {
        action_special              = true,
        special_releases_action_one = false,
        special_releases_action_two = true,
        promise_buffer              = 1.0,
    },
    lasgun_p1_m1 = {
        action_special              = true,
        action_reload               = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        reload_releases_action_one  = true,
        reload_releases_action_two  = false,
        promise_buffer              = 1.0,
    },
    lasgun_p1_m2 = {
        action_special              = true,
        action_reload               = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        reload_releases_action_one  = true,
        reload_releases_action_two  = false,
        promise_buffer              = 1.0,
    },
    lasgun_p1_m3 = {
        action_special              = true,
        action_reload               = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        reload_releases_action_one  = true,
        reload_releases_action_two  = false,
        promise_buffer              = 1.0,
    },
    lasgun_p2_m1 = {
        action_special              = true,
        action_reload               = true,
        special_releases_action_one = false,
        special_releases_action_two = true,
        reload_releases_action_one  = false,
        reload_releases_action_two  = true,
        promise_buffer              = 1.0,
    },
    lasgun_p2_m2 = {
        action_special              = true,
        action_reload               = true,
        special_releases_action_one = false,
        special_releases_action_two = true,
        reload_releases_action_one  = false,
        reload_releases_action_two  = true,
        promise_buffer              = 1.0,
    },
    lasgun_p2_m3 = {
        action_special              = true,
        action_reload               = true,
        special_releases_action_one = false,
        special_releases_action_two = true,
        reload_releases_action_one  = false,
        reload_releases_action_two  = true,
        promise_buffer              = 1.0,
    },
    lasgun_p3_m1 = {
        action_special              = true,
        action_reload               = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        reload_releases_action_one  = true,
        reload_releases_action_two  = false,
        promise_buffer              = 1.0,
    },
    lasgun_p3_m2 = {
        action_special              = true,
        action_reload               = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        reload_releases_action_one  = true,
        reload_releases_action_two  = false,
        promise_buffer              = 1.0,
    },
    lasgun_p3_m3 = {
        action_special              = true,
        action_reload               = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        reload_releases_action_one  = true,
        reload_releases_action_two  = false,
        promise_buffer              = 1.0,
    },
    laspistol_p1_m1 = {
        action_special              = true,
        action_reload               = true,
        ignore_active_special       = true, -- Without this, Special wont get promised while shooting
        special_releases_action_one = true,
        special_releases_action_two = false,
        reload_releases_action_one  = true,
        reload_releases_action_two  = false,
        promise_buffer              = 1.0,
    },
    laspistol_p1_m3 = {
        action_special              = true,
        action_reload               = true,
        ignore_active_special       = true, -- Without this, Special wont get promised while shooting
        special_releases_action_one = true,
        special_releases_action_two = false,
        reload_releases_action_one  = true,
        reload_releases_action_two  = false,
        promise_buffer              = 1.0,
    },
    plasmagun_p1_m1 = {
        action_special              = false,
        action_reload               = true,
        special_releases_action_one = false,
        special_releases_action_two = false,
        reload_releases_action_one  = false,
        reload_releases_action_two  = false,
    },
    shotgun_p1_m1 = {
        pressing_buffer             = 0.2,
        action_special              = true,
        action_reload               = true,
        special_requires_ammo       = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        reload_releases_action_one  = true,
        reload_releases_action_two  = false,
        promise_buffer              = 1.0,
    },
    shotgun_p1_m2 = {
        pressing_buffer             = 0.2,
        action_special              = true,
        action_reload               = true,
        special_requires_ammo       = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        reload_releases_action_one  = true,
        reload_releases_action_two  = false,
        promise_buffer              = 1.0,
    },
    shotgun_p1_m3 = {
        pressing_buffer             = 0.2,
        action_special              = true,
        action_reload               = true,
        special_requires_ammo       = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        reload_releases_action_one  = true,
        reload_releases_action_two  = false,
        promise_buffer              = 1.0,
    },
    shotgun_p2_m1 = {
        pressing_buffer             = 0.2,
        action_special              = true,
        action_reload               = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        reload_releases_action_one  = true,
        reload_releases_action_two  = false,
        promise_buffer              = 1.0,
    },
    shotgun_p4_m1 = {
        pressing_buffer             = 0.2,
        action_special              = true,
        action_reload               = true,
        special_needs_charges       = 1,
        special_releases_action_one = true,
        special_releases_action_two = false,
        reload_releases_action_one  = true,
        reload_releases_action_two  = false,
        promise_buffer              = 1.0,
    },
    shotgun_p4_m2 = {
        pressing_buffer             = 0.2,
        action_special              = true,
        action_reload               = true,
        special_needs_charges       = 1,
        special_releases_action_one = true,
        special_releases_action_two = false,
        reload_releases_action_one  = true,
        reload_releases_action_two  = false,
        promise_buffer              = 1.0,
    },
    stubrevolver_p1_m1 = {
        action_special              = true,
        action_reload               = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        reload_releases_action_one  = true,
        reload_releases_action_two  = false,
        promise_buffer              = 1.0,
    },
    stubrevolver_p1_m2 = {
        action_special              = true,
        action_reload               = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        reload_releases_action_one  = true,
        reload_releases_action_two  = false,
        promise_buffer              = 1.0,
    },
    shotpistol_shield_p1_m1 = {
        action_special              = true,
        action_reload               = true,
        special_releases_action_one = true,
        special_releases_action_two = true,
        reload_releases_action_one  = true,
        reload_releases_action_two  = true,
        promise_buffer              = 1.0,
    },
    dual_autopistols_p1_m1 = {
        action_special              = true,
        action_reload               = true,
        special_releases_action_one = true,
        special_releases_action_two = true,
        reload_releases_action_one  = true,
        reload_releases_action_two  = false,
        promise_buffer              = 1.0,
    },
    dual_stubpistols_p1_m1 = {
        action_special              = true,
        action_reload               = true,
        special_releases_action_one = true,
        special_releases_action_two = true,
        reload_releases_action_one  = true,
        reload_releases_action_two  = false,
        promise_buffer              = 1.0,
    },
    needlepistol_p1_m1 = {
        action_special              = true,
        action_reload               = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        reload_releases_action_one  = true,
        reload_releases_action_two  = false,
        promise_buffer              = 1.0,
    },
    needlepistol_p1_m2 = {
        action_special              = true,
        action_reload               = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        reload_releases_action_one  = true,
        reload_releases_action_two  = false,
        promise_buffer              = 1.0,
    },
    ogryn_gauntlet_p1_m1 = {
        action_special              = true,
        action_reload               = true,
        special_releases_action_one = true,
        special_releases_action_two = true,
        reload_releases_action_one  = true,
        reload_releases_action_two  = true,
        promise_buffer              = 1.2,
    },
    ogryn_heavystubber_p1_m1 = {
        action_special              = true,
        action_reload               = true,
        special_releases_action_one = true,
        special_releases_action_two = true,
        reload_releases_action_one  = true,
        reload_releases_action_two  = true,
        promise_buffer              = 1.0,
    },
    ogryn_heavystubber_p1_m2 = {
        action_special              = true,
        action_reload               = true,
        special_releases_action_one = true,
        special_releases_action_two = true,
        reload_releases_action_one  = true,
        reload_releases_action_two  = true,
        promise_buffer              = 1.0,
    },
    ogryn_heavystubber_p1_m3 = {
        action_special              = true,
        action_reload               = true,
        special_releases_action_one = true,
        special_releases_action_two = true,
        reload_releases_action_one  = true,
        reload_releases_action_two  = true,
        promise_buffer              = 1.0,
    },
    ogryn_heavystubber_p2_m1 = {
        action_special              = true,
        action_reload               = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        reload_releases_action_one  = true,
        reload_releases_action_two  = false,
        promise_buffer              = 1.0,
    },
    ogryn_heavystubber_p2_m2 = {
        action_special              = true,
        action_reload               = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        reload_releases_action_one  = true,
        reload_releases_action_two  = false,
        promise_buffer              = 1.0,
    },
    ogryn_heavystubber_p2_m3 = {
        action_special              = true,
        action_reload               = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        reload_releases_action_one  = true,
        reload_releases_action_two  = false,
        promise_buffer              = 1.0,
    },
    ogryn_rippergun_p1_m1 = {
        action_special              = true,
        action_reload               = true,
        special_releases_action_one = true,
        special_releases_action_two = true,
        reload_releases_action_one  = true,
        reload_releases_action_two  = false,
        promise_buffer              = 1.2,
    },
    ogryn_rippergun_p1_m2 = {
        action_special              = true,
        action_reload               = true,
        special_releases_action_one = true,
        special_releases_action_two = true,
        reload_releases_action_one  = true,
        reload_releases_action_two  = false,
        promise_buffer              = 1.2,
    },
    ogryn_rippergun_p1_m3 = {
        action_special              = true,
        action_reload               = true,
        special_releases_action_one = true,
        special_releases_action_two = true,
        reload_releases_action_one  = true,
        reload_releases_action_two  = false,
        promise_buffer              = 1.2,
    },
    ogryn_thumper_p1_m1 = {
        action_special              = true,
        action_reload               = true,
        special_releases_action_one = false,
        special_releases_action_two = false,
        reload_releases_action_one  = false,
        reload_releases_action_two  = false,
        promise_buffer              = 1.0,
    },
    ogryn_thumper_p1_m2 = {
        action_special              = true,
        action_reload               = true,
        special_releases_action_one = false,
        special_releases_action_two = false,
        reload_releases_action_one  = false,
        reload_releases_action_two  = false,
        promise_buffer              = 1.0,
    },
}

return weapons
