local weapons = {
    chainsword_p1_m1 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.3,
    },
    chainsword_p1_m2 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.3,
    },
    chainsword_2h_p1_m1 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.3,
    },
    chainsword_2h_p1_m2 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.3,
    },
    chainaxe_p1_m1 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.5,
    },
    chainaxe_p1_m2 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.5,
    },
    combataxe_p1_m1 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    combataxe_p1_m2 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    combataxe_p1_m3 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    combataxe_p2_m1 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    combataxe_p2_m2 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    combataxe_p2_m3 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    combataxe_p3_m1 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    combataxe_p3_m2 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.3,
    },
    combataxe_p3_m3 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.3,
    },
    combatknife_p1_m1 = {
        action_special              = true,
        interrupt_sprinting_special = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    combatknife_p1_m2 = {
        action_special              = true,
        interrupt_sprinting_special = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    combatsword_p1_m1 = {
        action_special              = true,
        special_parry               = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    combatsword_p1_m2 = {
        action_special              = true,
        special_parry               = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    combatsword_p1_m3 = {
        action_special              = true,
        special_parry               = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    combatsword_p2_m1 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    combatsword_p2_m2 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    combatsword_p2_m3 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    combatsword_p3_m1 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    combatsword_p3_m2 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    combatsword_p3_m3 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    forcesword_p1_m1 = {
        pressing_buffer             = 0.2,
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.3,
    },
    forcesword_p1_m2 = {
        pressing_buffer             = 0.2,
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.3,
    },
    forcesword_p1_m3 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    powermaul_p1_m1 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    powermaul_p1_m2 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    powermaul_p1_m3 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    powermaul_2h_p1_m1 = {
        action_special              = true,
        ignore_active_special       = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    powersword_p1_m1 = {
        action_special              = true,
        ignore_active_special       = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    powersword_p1_m2 = {
        action_special              = true,
        ignore_active_special       = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    thunderhammer_2h_p1_m1 = {
        action_special              = true,
        ignore_active_special       = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    thunderhammer_2h_p1_m2 = {
        action_special              = true,
        ignore_active_special       = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    ogryn_combatblade_p1_m1 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    ogryn_combatblade_p1_m2 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    ogryn_combatblade_p1_m3 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    ogryn_club_p1_m1 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    ogryn_club_p1_m2 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.3,
    },
    ogryn_club_p1_m3 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.3,
    },
    ogryn_club_p2_m1 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    ogryn_club_p2_m2 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    ogryn_club_p2_m3 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    ogryn_powermaul_p1_m1 = {
        action_special              = true,
        ignore_active_special       = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    ogryn_powermaul_p1_m2 = {
        action_special              = true,
        ignore_active_special       = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    ogryn_powermaul_p1_m3 = {
        action_special              = true,
        ignore_active_special       = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    ogryn_powermaul_slabshield_p1_m1 = {
        action_special              = false,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    ogryn_pickaxe_2h_p1_m1 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.5,
    },
    ogryn_pickaxe_2h_p1_m2 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.5,
    },
    ogryn_pickaxe_2h_p1_m3 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.5,
    },
    autogun_p1_m1 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 0.7,
    },
    autogun_p1_m2 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 0.7,
    },
    autogun_p1_m3 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 0.7,
    },
    autogun_p2_m1 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 0.7,
    },
    autogun_p2_m2 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 0.7,
    },
    autogun_p2_m3 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 0.7,
    },
    autogun_p3_m1 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 0.7,
    },
    autogun_p3_m2 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 0.7,
    },
    autogun_p3_m3 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 0.7,
    },
    autopistol_p1_m1 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 0.7,
    },
    bolter_p1_m1 = {
        interval_do_promise         = 0.2,
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = true,
        promise_buffer              = 0.7,
    },
    boltpistol_p1_m1 = {
        interval_do_promise         = 0.2,
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = true,
        promise_buffer              = 0.7,
    },
    flamer_p1_m1 = {
        action_special              = true,
        special_releases_action_one = false,
        special_releases_action_two = false,
        promise_buffer              = 0.7,
    },
    forcestaff_p1_m1 = {
        action_special              = true,
        special_releases_action_one = false,
        special_releases_action_two = true,
        promise_buffer              = 0.7,
    },
    forcestaff_p2_m1 = {
        action_special              = true,
        special_releases_action_one = false,
        special_releases_action_two = true,
        promise_buffer              = 0.7,
    },
    forcestaff_p3_m1 = {
        action_special              = true,
        special_releases_action_one = false,
        special_releases_action_two = true,
        promise_buffer              = 0.7,
    },
    forcestaff_p4_m1 = {
        action_special              = true,
        special_releases_action_one = false,
        special_releases_action_two = true,
        promise_buffer              = 0.7,
    },
    lasgun_p1_m1 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 0.7,
    },
    lasgun_p1_m2 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 0.7,
    },
    lasgun_p1_m3 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 0.7,
    },
    lasgun_p2_m1 = {
        action_special              = true,
        special_releases_action_one = false,
        special_releases_action_two = true,
        promise_buffer              = 0.7,
    },
    lasgun_p2_m2 = {
        action_special              = true,
        special_releases_action_one = false,
        special_releases_action_two = true,
        promise_buffer              = 0.7,
    },
    lasgun_p2_m3 = {
        action_special              = true,
        special_releases_action_one = false,
        special_releases_action_two = true,
        promise_buffer              = 0.7,
    },
    lasgun_p3_m1 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 0.7,
    },
    lasgun_p3_m2 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 0.7,
    },
    lasgun_p3_m3 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 0.7,
    },
    laspistol_p1_m1 = {
        action_special              = true,
        ignore_active_special       = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 0.7,
    },
    laspistol_p1_m3 = {
        action_special              = true,
        ignore_active_special       = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 0.7,
    },
    plasmagun_p1_m1 = {
        action_special              = false,
        special_releases_action_one = false,
        special_releases_action_two = false,
    },
    shotgun_p1_m1 = {
        pressing_buffer             = 0.2,
        action_special              = true,
        special_ammo                = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    shotgun_p1_m2 = {
        pressing_buffer             = 0.2,
        action_special              = true,
        special_ammo                = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    shotgun_p1_m3 = {
        pressing_buffer             = 0.2,
        action_special              = true,
        special_ammo                = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    shotgun_p2_m1 = {
        action_special              = true,
        ignore_active_special       = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 1.0,
    },
    stubrevolver_p1_m1 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 0.7,
    },
    stubrevolver_p1_m2 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = false,
        promise_buffer              = 0.7,
    },
    ogryn_gauntlet_p1_m1 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = true,
        promise_buffer              = 1.2,
    },
    ogryn_heavystubber_p1_m1 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = true,
        promise_buffer              = 0.7,
    },
    ogryn_heavystubber_p1_m2 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = true,
        promise_buffer              = 0.7,
    },
    ogryn_heavystubber_p1_m3 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = true,
        promise_buffer              = 0.7,
    },
    ogryn_rippergun_p1_m1 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = true,
        promise_buffer              = 1.2,
    },
    ogryn_rippergun_p1_m2 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = true,
        promise_buffer              = 1.2,
    },
    ogryn_rippergun_p1_m3 = {
        action_special              = true,
        special_releases_action_one = true,
        special_releases_action_two = true,
        promise_buffer              = 1.2,
    },
    ogryn_thumper_p1_m1 = {
        action_special              = true,
        special_releases_action_one = false,
        special_releases_action_two = false,
        promise_buffer              = 0.7,
    },
    ogryn_thumper_p1_m2 = {
        action_special              = true,
        special_releases_action_one = false,
        special_releases_action_two = false,
        promise_buffer              = 0.7,
    },
}

return weapons
